### ISSUE TITLE
Nach dem Ändern des Repository Namens wird der alte Name zusätzlich angezeigt mit Fehler

### ISSUE THREAD

**Issue by Thorsten1502** [mycloudrevolution/Advanced-PRTG-Sensors#13]
Ich habe den Namen eines Repositorys geändert. Danach gibt es 2 Einträge. Das neue Name und der alte mit einem Fehler.

**Comment by eren-kemer** [comment]
PRTG unterstützt leider das Entfernen/Umbenennen von Channels (noch?) nicht. Dementsprechend kann da leider nichts gemacht werden.
Ich persönlich lege den Sensor dann einfach neu an.

**Comment by Thorsten1502** [comment]
Super - vielen Dank für die Info. Habe den Sensor neu angelegt und den Alten für die Historischen Daten pausiert.

**Comment by mycloudrevolution** [comment]
Ich habe hierfür auch bereits einen enhancement request eröffnet. 
Gerne auch so machen, eventuell kommt da mal eine Verbesserung.
