### ISSUE TITLE
PRTG - Veeam Script

### ISSUE THREAD

**Issue by HujinoKun** [mycloudrevolution/Advanced-PRTG-Sensors#14]
Hi,

Your script doesn't work on my PRTG (Windows Server 2016) linked with my Veeam Backup & Replication 9.5.

Veeam port : 9392 (Port used by the Veeam Backup & Replication console to connect to the backup server).

If i put 9392 port, my script given nothing.

But if i put your port i get some error.

Any idea ?

Best regards,

PS : Script name : https://gist.github.com/mycloudrevolution/713b2e4aa767257f84cc#file-prtg-veeam-sessionstats-ps1

**Comment by mycloudrevolution** [comment]
Hello,

Veeam Console Connection works on that Server?
Have tried the manual execution of the Script, or only in PRTG?

If you have tried the manual execution, what is the Error?

Best Regards,
Markus

**Comment by HujinoKun** [comment]
From memory there is.
Currently I launch it manually, as I announced using the port in your script I have error messages but if I use 9392 nothing displayed.

**Comment by mycloudrevolution** [comment]
Have you modifed any ports during Veeam B&R Setup? If so you need to modify also the Port in Console Login Window.

Might you please post the error message from PS Console here?

**Comment by HujinoKun** [comment]
Hello !

With your port i got this : 

```
Invoke-WebRequest : Impossible de se connecter au serveur distant
Au caractère C:\Program Files (x86)\PRTG Network Monitor\Custom Sensors\EXEXML\PRTG-VEEAM-SessionStats.ps1:11 : 12
+ $AuthXML = Invoke-WebRequest @Auth
+            ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation : (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExcepti 
   on
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
 
Indexation impossible dans un tableau Null.
Au caractère C:\Program Files (x86)\PRTG Network Monitor\Custom Sensors\EXEXML\PRTG-VEEAM-SessionStats.ps1:14 : 1
+ $Sessions = @{uri = "http://X.X.X.X:9399/api/reports/summary/job_ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation : (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray
 
Invoke-RestMethod : Impossible de valider l'argument sur le paramètre «Uri». L’argument est Null ou vide. Indiquez un 
argument qui n’est pas Null ou vide et réessayez.
Au caractère C:\Program Files (x86)\PRTG Network Monitor\Custom Sensors\EXEXML\PRTG-VEEAM-SessionStats.ps1:20 : 39
+ [xml]$SessionsXML = invoke-restmethod @Sessions
+                                       ~~~~~~~~~
    + CategoryInfo          : InvalidData : (:) [Invoke-RestMethod], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
 
Indexation impossible dans un tableau Null.
Au caractère C:\Program Files (x86)\PRTG Network Monitor\Custom Sensors\EXEXML\PRTG-VEEAM-SessionStats.ps1:27 : 1
+ $VMs = @{uri = "http://X.X.X.X:9399/api/reports/summary/vms_overv ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation : (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray
 
Invoke-RestMethod : Impossible de valider l'argument sur le paramètre «Uri». L’argument est Null ou vide. Indiquez un 
argument qui n’est pas Null ou vide et réessayez.
Au caractère C:\Program Files (x86)\PRTG Network Monitor\Custom Sensors\EXEXML\PRTG-VEEAM-SessionStats.ps1:33 : 34
+ [xml]$VMsXML = invoke-restmethod @VMs
+                                  ~~~~
    + CategoryInfo          : InvalidData : (:) [Invoke-RestMethod], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
```

With 9392 port nothing is happening : 

`PS C:\Users\Administrateur.WIN-OAANMH1TN57> C:\Program Files (x86)\PRTG Network Monitor\Custom Sensors\EXEXML\PRTG-VEEAM-SessionStats.ps1`

We didn't change any ports during Veeam B&R setup.

**Comment by mycloudrevolution** [comment]
Can you access the Veeam Enterprise Manager by Internet Explorer from this Server?
Sorry, at first iI thought you are talking about the native Veeam PowerShell Script...

**Comment by HujinoKun** [comment]
i've just Veeam B&R

**Comment by mycloudrevolution** [comment]
This Script only works with veeam ent. Manager. Try this one:
https://github.com/mycloudrevolution/Advanced-PRTG-Sensors/blob/master/Veeam/PRTG-VeeamBRStats.ps1

But you need to Install veeam Console on your prtg Server first.

**Comment by HujinoKun** [comment]
I'll try.

But i prefer your script with manager, my chief will install Veeam ent. Manager

Thank's for your helping

**Comment by mycloudrevolution** [comment]
Thats why i mentioned that you need to install Veeam Console on PRTG Server to use the other Script...

Do you think the issue Can be closed?

**Comment by HujinoKun** [comment]
Not yet

In case for the users of Windows Server 2016 ;) like that I could give you the new manners.

**Comment by mycloudrevolution** [comment]
OK, then might you please be more exact with your Problem description:

- Which script do you use at the moment?
- Which OS Version is the Server where PS Script is Executed
- Which PS Version uses the Server where PS Script is Executed
- Which Veeam Version do you Use?

**Comment by HujinoKun** [comment]
At the moment i try this script : 

> https://gist.github.com/mycloudrevolution/713b2e4aa767257f84cc#file-prtg-veeam-sessionstats-ps1

I using Windows Server 2016 (PS version : 5.1.14393.1480) for my PRTG Server and using Windows Server 2008 R2 for Veeam (PS version : 2.0).

Veeam Version : 9.5

**Comment by mycloudrevolution** [comment]
This Script does not require the Veeam PowerShell Module. But you need a Veeam Enterprise Manager and Veeam Ent. Plus License to gather the Stats.
I have not verified the Script with Windows 2016 Server and PS Version 5.1.

**Comment by HujinoKun** [comment]
https://gist.github.com/mycloudrevolution/713b2e4aa767257f84cc#file-prtg-veeam-sessionstats-ps1

working with 9399 port (http) i didn't have error and the script executed successfully.

For result, i'll try tomorrow ;)

**Comment by HujinoKun** [comment]
up ^^

**Comment by mycloudrevolution** [comment]
If no Data or Error is returned the possible problem is that no veeam Backup server is configured in ent. Manager. Have you checked that?

**Comment by HujinoKun** [comment]
![2017-08-03 17_48_17-veeam backup enterprise manager](https://user-images.githubusercontent.com/23108069/28930672-fb09e6bc-7873-11e7-9a76-75280bdc4025.png)

**Comment by mycloudrevolution** [comment]
Sorry, then I am not able to do more remote Diag.
I have verified the Script a few days ago with the latest version and it has worked fine...

**Comment by HujinoKun** [comment]
Which port did you put in @{uri link ?

**Comment by HujinoKun** [comment]
Script working now i have some results.

But in my PRTG Server i have nothing about my GB Size, protected VM, sucessfull

Any idea ?
