### ISSUE TITLE
Job name

### ISSUE THREAD

**Issue by HujinoKun** [mycloudrevolution/Advanced-PRTG-Sensors#16]
Hello,

Is there a way to add in your script the names of the jobs as well as the virtual machines which are in the job that one test?

In kb veeam website, I found this : 

```
<MaxDurationBackupJobName>Backup_2014-10-18T044119</MaxDurationBackupJobName>
 <MaxDurationReplicaJobName>Fileserver02 Replication</MaxDurationReplicaJobName>
```

It's a good idea ?

Have a good day

**Comment by mycloudrevolution** [comment]
Hello,
this enhancement request ist for the "PRTG-VeeamBRStats.ps1" right?

I think thats a very important information. But I am not sure if a Monitoring system is the right place for that type of Info...

Best Regards
Markus
