### ISSUE TITLE
Exception thrown when Cloud Repository not connected

### ISSUE THREAD

**Issue by eren-kemer** [mycloudrevolution/Advanced-PRTG-Sensors#18]
When cloud repository is added to VBR Console but not connected(see image), the powershell script shows an exception, just before PRTG output.

![image](https://user-images.githubusercontent.com/4806188/32414555-4d8ee82e-c22a-11e7-8f0c-448ec1ac5d6a.png)

![image](https://user-images.githubusercontent.com/4806188/32414570-73410390-c22a-11e7-8901-c37e1eb93a3c.png)

Doesn't affect prtg output directly, but i assume this **should** be an error in PRTG.

```

Ausnahme beim Aufrufen von "SyncSpaceInfoToDb" mit 2 Argument(en):  "Failed to establish connect to the service provider"
In C:\Program Files (x86)\PRTG Network Monitor\Custom Sensors\EXEXML\PRTG-VeeamBRStats2.ps1:78 Zeichen:6
+                     [Veeam.Backup.Core.CBackupRepositoryEx]::SyncSpaceInfoToDb($r, $true)
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : Exception
```

**Comment by eren-kemer** [comment]
Don't know how(didn't find any way to) but perhasp you could check if the repository is connected.
Otherwise, maybe catch the exception and turn the sensor red?

**Comment by mycloudrevolution** [comment]
I think the problem is not cloud Repo specific.
All unailable Repositories should be effected (Server disconnected for example ).

Have you tried a simple Try / Catch around '[Veeam.Backup.Core.CBackupRepositoryEx]::SyncSpaceInfoToDb($r, $true)'?

I will try to create a test scenario inside my Lab for that Situationen.

**Comment by eren-kemer** [comment]
I'm not too familiar with powershell. Just tried to fiddle around to find the issue here.
I can test for you though, if needed.

**Comment by mycloudrevolution** [comment]
Might you please check this Version:
https://github.com/mycloudrevolution/Advanced-PRTG-Sensors/pull/21

in Debug Mode you should see the message: "SyncSpaceInfoToDb Failed" but no error should occure.

**Comment by eren-kemer** [comment]
Works as expected.
