### ISSUE TITLE
Output unexpected

### ISSUE THREAD

**Issue by dannyr1992** [mycloudrevolution/Advanced-PRTG-Sensors#34]
This script is great and has worked for many sites so far. However one site i am having an issue and wonder if anyone can help.

I have to run the script using the PS64.exe app so it can run in 64 bit for PRTG to work but when i do i get a strange output not the normal values.

Running the script locally in power shell works as expected.

Please see the cmdlet below , please can someone give me some advice.

`C:\Program Files (x86)\PRTG Network Monitor\Custom Sensors\EXEXML>PSx64.exe -f=P
RTG-VeeamBRStats.ps1
0:)</channel>
  <value>71</value>
  <unit>Percent</unit>
  <showChart>1</showChart>
  <showTable>1</showTable>
  <LimitMinWarning>20</LimitMinWarning>
  <LimitMinError>10</LimitMinError>
  <LimitMode>1</LimitMode>
</result>
</prtg>`

**Comment by eren-kemer** [comment]
This seems to be related to my closed issue #31.
The updated PSx64.exe was supposed to be published already, seems like it hasn't been.
I just messaged prtgtoolsfamily.com about it, will keep you updated.

**Comment by eren-kemer** [comment]
Seems like the newest version is already up.
Please make sure you got version 18.1.1.6 from prtgtoolsfamily.com
Also, please try to run PSx64.exe with the -raw parameter.
"PSx64.exe -f=PRTG-VeeamBRStats.ps1 -raw"

**Comment by dannyr1992** [comment]
Thanks for your response and help , i will give this a go and report my result.

**Comment by dannyr1992** [comment]
Nice easy fix.:) Worked a treat.

Thanks a lot 👍
