### ISSUE TITLE
PRTG - VEEAM Powershell Script Problems

### ISSUE THREAD

**Issue by jhillenb1961** [mycloudrevolution/Advanced-PRTG-Sensors#35]
Hello,

we would like to use PRTG to monitor Veeam B&R Enterprise Version 9.5 Up3 (PRTG is installed on Windows 2012 R2 Server).

We found some Powershell scripts to realize this issue:
Example:
https://kb.paessler.com/en/topic/72030-monitoring-veeam-backup-replication-without-veeam-enterprise-manager
https://mycloudrevolution.com/2016/03/21/veeam-prtg-sensor-reloaded/

We install the Veeam Powershell Extension on PRTG Server. Listing Veeam Command Applets modules in Powershell was successfull. Modules load automatically after example: rebooting the server.

Installation Process:
Set-Alias installutil $env:windir\Microsoft.NET\Framework64\v4.0.30319\installutil.exe
installutil "C:\Program Files\Veeam\Backup and Replication\Backup\Veeam.Backup.PowerShell.dll"
add-pssnapin VeeamPSSnapIn
Get-Command -Module VeeamPSSnapIn 

The plugins get automatically reloaded after rebooting the server.

We Download the Tool PSx64.exe http://prtgtoolsfamily.com/downloads/sensors 
and copy the file to:
C:\Program Files (x86)\PRTG Network Monitor\Custom Sensors\EXEXML
 
We download the PRTG-VeeamBRStats.ps1 and store it on same directory  

We create a sensor as described (see documentatation) and get the following error message, located in PRTG Log File

Connect-VBRServer : Veeam PowerShell snap-in was loaded from an incorrect location.
At C:\Program Files (x86)\PRTG Network Monitor\custom sensors\EXEXML\PRTG-VeeamBRStats.ps1:
Connect-VBRServer -Server $BRHost
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CategoryInfo          : InvalidOperation: (:) [Connect-VBRServer], Exception
FullyQualifiedErrorId : InstallationCheckerErrorId,Veeam.Backup.PowerShell.
Cmdlets.ConnectVBRServer

C:\Program Files (x86)\PRTG Network Monitor\custom sensors\EXEXML\PRTG-VeeamBRStats.ps1

Error: BRHost Connection Failed At line:1 char:1 &'C:\Program Files (x86)\PRTG Network Monitor\custom 
sensors\EXEXML\PRTG-VeeamBR ...

CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,
PRTG-VeeamBRStats.ps1

Starting to Process Connection to -BRHOST vde.dasi03.local.vde.com ... Connecting BRHost...

I am testing the script on a simple command prompt: 
PSx64.exe -f="PRTG-VeeamBRStats.ps1" -p="-BRHOST=VDE-DASI03.local.vde.com"  
Error still the same:

Veeam PowerShell snap-in was loaded from an incorrect location.

I think there is something wrong with PSx64.exe.

Did someone have a good idea to fix the problem
Thanks and best regards
Jürgen

**Comment by mycloudrevolution** [comment]
Hello @jhillenb1961,

What's the reason for not installing the full console? 

Best regards 
Markus

**Comment by jhillenb1961** [comment]
Hello Markus,
you want to say, why I dont install VEEAM Backup Console to PRTG Server ? Right?
Best Regards Jürgen

**Comment by mycloudrevolution** [comment]
Right.

**Comment by jhillenb1961** [comment]
Thank you - that fix the problem !!!

**Comment by mycloudrevolution** [comment]
I'm really pleased.
