### ISSUE TITLE
Veeam Update 9.4

### ISSUE THREAD

**Issue by Pacman1988** [mycloudrevolution/Advanced-PRTG-Sensors#38]
After Upgrading from Veeam BR 9.3a to 9.4. 

The sensor shows the following error: 

XML: The returned XML does not match the expected schema. (code: PE233) -- JSON: The returned JSON does not match the expected structure (Invalid JSON.). (code: PE231)

**Comment by mycloudrevolution** [comment]
Have you already upgraded the console / PS SnapIn on the PRTG Probe?

**Comment by Pacman1988** [comment]
Yes I have.

**Comment by mycloudrevolution** [comment]
Have you tried to execute the Script manually in the PowerShell Console?

**Comment by Pacman1988** [comment]
It works again without any interaction from my side. Weird.
