### ISSUE TITLE
Colon in the repo name

### ISSUE THREAD

**Issue by foorschtbar** [mycloudrevolution/Advanced-PRTG-Sensors#4]
The xml is malformed when a colon is in the repo name.

**Comment by mycloudrevolution** [comment]
Can you tell which script you have used?

If PSx64.exe is in Use have you tried the "-raw" switch?
An other user had a similas issue with this output:
<channel>REPO - LD301 (F:)</channel>

**Comment by foorschtbar** [comment]
We've had also a repo with a Driveletter in it. With the -raw switch we get this error: 
`XML: XML Parser mismatch: Wanted </>, got </channel>`

**Comment by mycloudrevolution** [comment]
@foorschtbar do you get this error during manual execution or in PRTG?

More Logs would help me. Can you please execute the Script in with the following command:

CMD: PSx64.EXE -raw -f=<PRTG Script>

And attach the output?

**Comment by foorschtbar** [comment]
This error was from PRTG, but this is from the cmd:

With -raw:
`C:\Program Files (x86)\PRTG Network Monitor\Custom Sensors\EXEXML>PSx64.exe -raw -f="PRTG-VeeamBRstats.ps1" -p="xxx.local"
0`

Without -raw:
`C:\Program Files (x86)\PRTG Network Monitor\Custom Sensors\EXEXML>PSx64.exe -f="PRTG-VeeamBRstats.ps1" -p="xxx.local"
0:)</channel>
<value>39</value>
<unit>Percent</unit>
<showChart>1</showChart>
<showTable>1</showTable>
<LimitMinWarning>20</LimitMinWarning>
<LimitMinError>10</LimitMinError>
<LimitMode>1</LimitMode>
</result>
</prtg>`

Without colon:
`C:\Program Files (x86)\PRTG Network Monitor\Custom Sensors\EXEXML>PSx64.exe -f="
PRTG-VeeamBRstats.ps1" -p="medelo-veeam.medelo.local"
0:Starting to Process Connection to medelo-veeam.medelo.local ...
Connecting BRHost...
<prtg>
<result>
<channel>Successful-Backups</channel>
<value>16</value>
<showChart>1</showChart>
<showTable>1</showTable>
[...]
<showChart>1</showChart>
<showTable>1</showTable>
<LimitMinWarning>20</LimitMinWarning>
<LimitMinError>10</LimitMinError>
<LimitMode>1</LimitMode>
</result>
</prtg>`

**Comment by mycloudrevolution** [comment]
I am confused... why do you add 

> 0

to the command?

The XML schema looks good. maybe is a screenshot clearer.

**Comment by foorschtbar** [comment]
This is the return code from PSx64.

It seams, that the PSx64 is the problem. I write my own PSx64 and now i have no problems with the colons.

https://kb.paessler.com/en/topic/32033-is-it-possible-to-use-the-64bit-version-of-powershell-with-prtg
