### ISSUE TITLE
Add ability to monitor Cloud Repositories

### ISSUE THREAD

**Issue by homern** [mycloudrevolution/Advanced-PRTG-Sensors#40]
with Get-VBRBackupRepository on a Cloud Repository the Sizes return with -1 so it Calculates to 100% Free Space

**Comment by mycloudrevolution** [comment]
Thanks for reporting this issue.

Might you please share the return of this command to verify a possible workaround:
```
Get-VBRBackupRepository | Select Type
```

**Comment by homern** [comment]
thanks for the fast reaction, the output is:

PS C:\_XX\> Get-VBRBackupRepository | Select Type
Type
CifsShare
Cloud
PS C:\_XX\>

**Comment by homern** [comment]
i also get an Exception at line 169 if I don't remove the .tolower() for this Repo, the CIFS is working fine

`$HostName = $(Get-VBRServer | Where-Object {$_.Id -eq $r.HostId}).Name.ToLower()`

> C:\_MTF\FreeSpace\Untitled1.ps1 : You cannot call a method on a null-valued expression.
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Untitled1.ps1
 
> C:\_XX\Untitled1.ps1 : at Get-vPCRepoInfo<Process>, C:\_MTF\FreeSpace\Untitled1.ps1: line 169
at <ScriptBlock>, C:\_XX\Untitled1.ps1: line 510
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Untitled1.ps1

**Comment by mycloudrevolution** [comment]
Might you please verify the Version of the script in PR #41

**Comment by homern** [comment]
this works now without the Error Message for the Cloud Repo and also Removes the Cloud Repo (as said in the Commit)

**Comment by homern** [comment]
for the moment its ok, but for the long run it would be nice to monitor the Storage left in Cloud Backup Repos

**Comment by mycloudrevolution** [comment]
I fully agree with you.

I will try to build a test environment for that that feature requests. But that will take some time.

**Comment by homern** [comment]
ok, I will close the Issue now and wait for the feature

thanks

**Comment by mycloudrevolution** [comment]
#42 is also about this request

**Comment by mycloudrevolution** [comment]
Might you please test the new version:
https://github.com/mycloudrevolution/Advanced-PRTG-Sensors/blob/IncludeCloudRepos/Veeam/PRTG-VeeamBRStats.ps1
