### ISSUE TITLE
Wrong XML format

### ISSUE THREAD

**Issue by Support-DataExpertise** [mycloudrevolution/Advanced-PRTG-Sensors#46]
Hi,

I'm having an issue with the utilization of the script.
When I run the script on the probe itself, the script return me something like that:

PS C:\Program Files (x86)\PRTG Network Monitor\Custom Sensors\EXEXML> .\PSx64.exe -f="PRTG-VeeamBRStats.ps1"

`0:<prtg>
<result>
  <channel>Successful-Backups</channel>
  <value>5</value>
  <showChart>1</showChart>
  <showTable>1</showTable>
</result>
.....`

I don't pass any parameters because I modified the BRHost variable into my script.
But when I setup PRTG to run the script, this is what it gives me :

![2020-01-03_09-21](https://user-images.githubusercontent.com/59469367/71714127-db2f0b00-2e0c-11ea-913a-6afaa9cda2bb.png)

This is what is setup into PRTG : 

![2020-01-03_09-39](https://user-images.githubusercontent.com/59469367/71714168-087bb900-2e0d-11ea-9cc1-0ec218c80b32.png)

Thanks for your help and Happy new year !

**Comment by mycloudrevolution** [comment]
Hi,

this issue is typically based on special characters (like "\ > <") in your Repo names.

Might you please execute the Script in Debug Mode and share the Result?

`C:\temp\PRTG-VeeamBRStats.ps1 -Debug`

**Comment by Support-DataExpertise** [comment]
I'm running the command on the server with : `.\PSx64.exe -f="PRTG-VeeamBRStats.ps1" -Debug` and it returns me the same result.

**Comment by mycloudrevolution** [comment]
Please run the command directly in PS without PSx64.exe

**Comment by Support-DataExpertise** [comment]
I donwloaded the latest version of the script and it worked
