### ISSUE TITLE
Issue on PRTG with Custom Sensor

### ISSUE THREAD

**Issue by jonnyj192** [mycloudrevolution/Advanced-PRTG-Sensors#7]
When trying to use this for PRTG reporting i get the following issue? could you help me please: 

XML: The returned XML does not match the expected schema. (code: PE233) -- JSON: The returned JSON does not match the expected structure (Invalid JSON.). (code: PE231)

**Comment by mycloudrevolution** [comment]
Sure, 
Might you please execute the Script in cmd shell and share the result? 
Sensor log will also be awsome.

**Comment by jonnyj192** [comment]
Report of Sensor: File "C:\Program Files (x86)\PRTG Network Monitor\custom sensors\EXEXML\PRTG.ps1" not found.

Report of Sensor.Data: 
Data['blockedsens'].asString := '';
Data['canlinux'].asString := '0';
Data['channelinfos'].asString := '{}';
Data['channelnames'].asString := '';
Data['exefile'].asString := 'PSx64.exe';
Data['exeparams'].asString := '-f=PRTG.ps1 -raw';
Data['fastcount'].asString := '0';
Data['host'].asString := '172.16.3.2';
Data['hostv6'].asString := '';
Data['inerror'].asString := '1';
Data['interfacenumber'].asString := '';
Data['inum'].asString := '';
Data['ipversion'].asString := '0';
Data['isexesensor'].asString := '1';
Data['lastmsg'].asString := '#Y2 @#O233 @#O231[Invalid JSON.]';
Data['lastuptime'].asString := '0';
Data['linuxlogindomain'].asString := '';
Data['linuxloginpassword'].asString := '***';
Data['monitorchange'].asString := '';
Data['mutexname'].asString := '';
Data['reboot'].asString := '42774.6879382407';
Data['reqmsginterval'].asString := '60';
Data['resultfile'].asString := 'Result of Sensor 4534.txt';
Data['sensorid'].asString := '4534';
Data['simulate'].asString := '0';
Data['timeout'].asString := '60';
Data['tlsexplicit_default'].asString := '';
Data['tlsexplicit_ftp'].asString := '';
Data['tlsexplicit_imap'].asString := '';
Data['tlsexplicit_pop3'].asString := '';
Data['tlsexplicit_port'].asString := '';
Data['tlsexplicit_smtp'].asString := '';
Data['uptimecount'].asString := '0';
Data['usednstime'].asString := '0';
Data['usewindowsauthentication'].asString := '1';
Data['windowslogindomain'].asString := '
Data['windowsloginpassword'].asString := '
Data['windowsloginusername'].asString := '
Data['writeresult'].asString := '1';

**Comment by jonnyj192** [comment]
That is the powershell command ran through CMD, I have xxx out the point which are private. 

Thanks for your help with this. 

X:\>powershell "& 'C:\Program Files (x86)\PRTG Network Monitor\custom sensors\EX
EXML\PRTG.ps1'"
Starting to Process Connection to XXXXXXXXXX
Connecting BRHost...
<prtg>
<result>
<channel>Successful-Backups</channel>
<value>1</value>
<showChart>1</showChart>
<showTable>1</showTable>
</result>
<result>
<channel>Warning-Backups</channel>
<value>0</value>
<showChart>1</showChart>
<showTable>1</showTable>
<LimitMaxWarning>0</LimitMaxWarning>
<LimitMode>1</LimitMode>
</result>
<result>
<channel>Failes-Backups</channel>
<value>0</value>
<showChart>1</showChart>
<showTable>1</showTable>
<LimitMaxError>0</LimitMaxError>
<LimitMode>1</LimitMode>
</result>
<result>
<channel>Failed-Backups</channel>
<value>0</value>
<showChart>1</showChart>
<showTable>1</showTable>
<LimitMaxError>0</LimitMaxError>
<LimitMode>1</LimitMode>
</result>
<result>
<channel>Running-Backups</channel>
<value>0</value>
<showChart>1</showChart>
<showTable>1</showTable>
</result>
<result>
<channel>Successful-BackupCopys</channel>
<value>0</value>
<showChart>1</showChart>
<showTable>1</showTable>
</result>
<result>
<channel>Warning-BackupCopys</channel>
<value>0</value>
<showChart>1</showChart>
<showTable>1</showTable>
<LimitMaxWarning>0</LimitMaxWarning>
<LimitMode>1</LimitMode>
</result>
<result>
<channel>Failes-BackupCopys</channel>
<value>0</value>
<showChart>1</showChart>
<showTable>1</showTable>
<LimitMaxError>0</LimitMaxError>
<LimitMode>1</LimitMode>
</result>
<result>
<channel>Failed-BackupCopys</channel>
<value>0</value>
<showChart>1</showChart>
<showTable>1</showTable>
<LimitMaxError>0</LimitMaxError>
<LimitMode>1</LimitMode>
</result>
<result>
<channel>Running-BackupCopys</channel>
<value>0</value>
<showChart>1</showChart>
<showTable>1</showTable>
</result>
<result>
<channel>Idle-BackupCopys</channel>
<value>0</value>
<showChart>1</showChart>
<showTable>1</showTable>
</result>
<result>
<channel>Successful-Replications</channel>
<value>0</value>
<showChart>1</showChart>
<showTable>1</showTable>
</result>
<result>
<channel>Warning-Replications</channel>
<value>0</value>
<showChart>1</showChart>
<showTable>1</showTable>
<LimitMaxWarning>0</LimitMaxWarning>
<LimitMode>1</LimitMode>
</result>
<result>
<channel>Failes-Replications</channel>
<value>0</value>
<showChart>1</showChart>
<showTable>1</showTable>
<LimitMaxError>0</LimitMaxError>
<LimitMode>1</LimitMode>
</result>
<result>
<channel>Failed-Replications</channel>
<value>0</value>
<showChart>1</showChart>
<showTable>1</showTable>
<LimitMaxError>0</LimitMaxError>
<LimitMode>1</LimitMode>
</result>
<result>
<channel>Running-Replications</channel>
<value>0</value>
<showChart>1</showChart>
<showTable>1</showTable>
</result>
<result>
<channel>TotalBackupRead</channel>
<value>299</value>
<unit>Custom</unit>
<customUnit>GB</customUnit>
<showChart>1</showChart>
<showTable>1</showTable>
</result>
<result>
<channel>TotalBackupTransfer</channel>
<value>42</value>
<unit>Custom</unit>
<customUnit>GB</customUnit>
<showChart>1</showChart>
<showTable>1</showTable>
</result>
<result>
<channel>REPO - xxxxx</channel>
<value>48</value>
<unit>Percent</unit>
<showChart>1</showChart>
<showTable>1</showTable>
<LimitMinWarning>20</LimitMinWarning>
<LimitMinError>10</LimitMinError>
<LimitMode>1</LimitMode>
</result>
<result>
<channel>REPO – xxxxx2</channel>
<value>17</value>
<unit>Percent</unit>
<showChart>1</showChart>
<showTable>1</showTable>
<LimitMinWarning>20</LimitMinWarning>
<LimitMinError>10</LimitMinError>
<LimitMode>1</LimitMode>
</result>
</prtg>

**Comment by mycloudrevolution** [comment]
Hi,
might you please verify that the PS1 Script is on all Probes and the Core available.

The PRTG Sensor Log reports that PSx64.exe can not find it:

> Report of Sensor: File "C:\Program Files (x86)\PRTG Network Monitor\custom sensors\EXEXML\PRTG.ps1" not found.

**Comment by jonnyj192** [comment]
HI, 

When i change the name of the script and ran it again i got the below error. 
"The system cannot find the file specified" which is when it had a false name. 

Just to confirm, the server which has the probe on is where i place the PSx64.exe and the PS1 script? all the data from the probe goes back to our central server offsite. 

Thanks

**Comment by mycloudrevolution** [comment]
Hi,

The manual execution is not the Problem. I think the execution vie PRTG is the Problem.
Is on all Probes where the PSx64.exe also the PS1 script located?

Yes, you are right the Probe for the Device where the Sensor is created executes the Script.

**Comment by jonnyj192** [comment]
![image](https://cloud.githubusercontent.com/assets/25668147/23017021/95126126-f430-11e6-8322-2ffdf0e8aa98.png)


This is how its set up on PTRG, please could you advise on this situation? 

Thanks

**Comment by jonnyj192** [comment]
I have now resolved this issue thanks.

**Comment by mycloudrevolution** [comment]
Might you please share the Solution?

**Comment by jonnyj192** [comment]
On this instance i recreated the PS1 file and edited DNS in the code to the IP address. This is now running however i'm still getting the Odd timeout which is frustrating... 

Thanks
